version: '3.8'

services:
  ai-agent:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MAIL_HOST=smtp.gmail.com
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
